spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: 0FY85WBCk_xdDKOfLSlM
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: https://${DOMAIN_NAME}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name

          kakao:
            client-name: kakao
            client-id: 7faee11710abb4932d0360ba40724295
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: https://${DOMAIN_NAME}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname

        google:
          client-name: google
          client-id: 678206844749-valeev05unb0m70vnlh1dbe7lr4fvj94.apps.googleusercontent.com
          client-secret: ${GOOGLE_CLIENT_SECRET}
          redirect-uri: https://${DOMAIN_NAME}/login/oauth2/code/google
          authorization-grant-type: authorization_code
          scope: profile

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jwt:
    secret: ${JWT_SECRET}
  application:
    name: wwm
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATASOURCE_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWD}
