name: Docker Image for WorkWithMe

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract version from build.gradle
      run: | 
        echo "VERSION=$(sed -n "s/^version = '\(.*\)'/\1/p" build.gradle)" >> "$GITHUB_ENV"
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg VERSION=${VERSION} --tag ${{secrets.DOCKER_USERNAME}}/workwithme:${VERSION} --tag ${{secrets.DOCKER_USERNAME}}/workwithme:latest

    - name: Log into Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{secrets.DOCKER_USERNAME}}/workwithme:${VERSION}
        docker push ${{secrets.DOCKER_USERNAME}}/workwithme:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SERVER_HOST}}
        username: ${{secrets.SERVER_USER}}
        password: ${{secrets.SERVER_PASSWORD}}
        port: ${{secrets.SERVER_SSH_PORT}}
        scripts: |
          docker pull ${{secrets.DOCKER_USERNAME}}/workwithme:latest
          docker stop wwme || true
          docker container rm wwme || true
          docker run -d \
            --name wwme \
            -p 8080:8080 \
            --env-file .env \
            --add-host host.docker.internal:host-gateway \
            ${{secrets.DOCKER_USERNAME}}/workwithme:latest
