name: Docker Image for WorkWithMe

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract version from build.gradle
      run: | 
        echo "VERSION=$(sed -n "s/^version = '\(.*\)'/\1/p" build.gradle)" >> "$GITHUB_ENV"
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg VERSION=${VERSION} --tag workwithme:${VERSION}

    - name: Log into Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image to Docker Hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/workwithme:${VERSION}
